import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import { Poppins, Roboto} from "next/font/google";
import "./globals.css";




const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

const josefin = Josefin_Sans({
  variable: "--font-poppins",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MOMENTUM",
  description: "Generated by create next app",
};

import AuthProvider from "./components/AuthProvider";
import StarBackground from "./components/StarBackground";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${poppins.variable}
           ${roboto.variable}
           ${josefin.variable}

          antialiased 
          relative 
          min-h-screen 
          bg-black
        `}
      >
        <AuthProvider>
          <StarBackground />
          {/* ALL YOUR CONTENT */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
